use agcp_mvp::crypto::{now_rfc3339, sign_action_envelope, signing_key_from_b64, verifying_key_to_b64};
use agcp_mvp::proto::{
    ActionEnvelope, AgentPassport, BudgetClaim, EvidencePointer, Intent, ProposedAction,
};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let args: Vec<String> = std::env::args().collect();
    if args.len() != 4 {
        eprintln!("usage: cargo run --example make_payload -- <low|high|read_only_write> <action_id> <run_id>");
        std::process::exit(2);
    }

    let profile = &args[1];
    let action_id = &args[2];
    let run_id = &args[3];

    // Deterministic demo key for local MVP only.
    let signing_key = signing_key_from_b64("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=")?;

    let (tool, args_json, evidence) = match profile.as_str() {
        "low" => (
            "repo.read",
            serde_json::json!({"path":"README.md"}),
            Vec::new(),
        ),
        "high" => (
            "k8s.apply",
            serde_json::json!({"cluster":"prod","manifest_hash":"sha256:demo"}),
            vec![EvidencePointer {
                evidence_type: "ticket".to_string(),
                reference: "JIRA-123".to_string(),
            }],
        ),
        "read_only_write" => (
            "k8s.apply",
            serde_json::json!({"cluster":"staging","manifest_hash":"sha256:demo"}),
            vec![EvidencePointer {
                evidence_type: "ticket".to_string(),
                reference: "JIRA-456".to_string(),
            }],
        ),
        _ => {
            eprintln!("unknown profile: {profile}");
            std::process::exit(2);
        }
    };

    let mut envelope = ActionEnvelope {
        action_id: action_id.to_string(),
        run_id: run_id.to_string(),
        agent_passport: AgentPassport {
            agent_id: "a-ops-07".to_string(),
            model_name: "model-x".to_string(),
            model_hash: "sha256:model-x".to_string(),
            policy_version: "p-12".to_string(),
            pubkey: verifying_key_to_b64(&signing_key.verifying_key()),
            runtime_attestation: "placeholder".to_string(),
        },
        intent: Intent {
            intent_type: "deploy_fix".to_string(),
            risk: "medium".to_string(),
            justification: Some("generated by regression example".to_string()),
        },
        proposed_action: ProposedAction {
            tool: tool.to_string(),
            args: args_json,
        },
        evidence,
        budget_claim: BudgetClaim {
            tool_calls: 1,
            write_actions: 1,
        },
        spawn_depth: 0,
        created_at: now_rfc3339(),
        sig: String::new(),
    };

    sign_action_envelope(&mut envelope, &signing_key)?;
    println!("{}", serde_json::to_string(&envelope)?);
    Ok(())
}
